# Don't print a new line at the start of the prompt
add_newline = false

format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$golang\
$nodejs\
$python\
$ruby\
$rust\
$aws\
$env_var\
$custom\
$cmd_duration\
$time\
$line_break\
$jobs\
$character\
"""

[aws]
disabled = false
format='on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[git_metrics]
disabled = false

[cmd_duration]
#style = "bold white"
min_time = 500

[directory]
#style = "bold fg:220"
style = "bold yellow"
truncation_length = 8

[git_commit]
only_detached = false

[time]
disabled = false
style = "fg:246"

[username]
show_always = true
style_user = "bold cyan"
