# Don't print a new line at the start of the prompt
add_newline = false

format = """
$username\
$hostname\
$kubernetes\
$directory\
$docker_context\
$package\
$golang\
$nodejs\
$python\
$ruby\
$rust\
$aws\
$env_var\
$custom\
$time\
$cmd_duration\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$character\
"""

[aws]
disabled = false
format='on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[cmd_duration]
#style = "bold white"
min_time = 500

[directory]
#style = "bold fg:220"
style = "bold yellow"
truncation_length = 8

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_commit]
only_detached = false
style = "green"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[time]
disabled = false
style = "dimmed italic"

[username]
show_always = true
style_user = "bold cyan"
